name: Check
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run check
      - if: failure()
        run: |
          yarn run fix
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: [mentemo-auto-fix]"
          git push
